auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_query_lookback: 30d  # New setting for Loki 3.x
  allow_structured_metadata: false
 

query_scheduler:
  max_outstanding_requests_per_tenant: 1000  # Optimized for performance

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory  # Disables Consul/memberlist
      replication_factor: 1
