# Use an official Python image
FROM python:3.10

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements_traffic.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt


# Copy only necessary files
#COPY . .
COPY traffic_consumer.py .

# Run the Python script
CMD ["python", "traffic_consumer.py"]
